import type { Conteudo } from './base';
import { INFANCIA } from './infancia';
import { ADOLESCENCIA } from './adolescencia';
import { ADULTO } from './adulto';
import { MATURIDADE } from './maturidade';
import { SISTEMICOS } from './sistemicos';
import { DESAFIOS } from './desafios';
import { VINCULOS } from './vinculos';
import { ESCOLHAS } from './escolhas';
import { PRIMEIROS } from './primeiros';
import { MUNDO } from './mundo';
import { SOCIAL } from './social';
import { CAMINHOS } from './caminhos';
import { MATERIAL } from './material';
import { TRAJETORIAS } from './trajetorias';
import { PROFISSAO } from './profissao';
import { POLITICA } from './politica';
import { COMPROMISSOS } from './compromissos';
import { NEGOCIOS_CONTEUDO } from './negocios';
import { BENS } from './bens';

export const CATALOGO: readonly Conteudo[] = [...COMPROMISSOS, ...NEGOCIOS_CONTEUDO, ...BENS, ...SISTEMICOS, ...SOCIAL, ...CAMINHOS, ...TRAJETORIAS, ...PROFISSAO, ...POLITICA, ...MATERIAL, ...DESAFIOS, ...INFANCIA, ...PRIMEIROS, ...ADOLESCENCIA, ...ADULTO, ...MATURIDADE, ...VINCULOS, ...ESCOLHAS, ...MUNDO];
