/**
 * As áreas de aprofundamento de cada ofício (REWORK 4): o que cada uma
 * SIGNIFICA e o que ela MUDA. Antes, Segurança, Dados, Infraestrutura e
 * Produto mostravam a mesma frase ("Cursos, leitura, os casos certos...") e
 * tinham o mesmo efeito (+2 de desempenho). Agora cada área diz o que é e
 * puxa a vida para um lado:
 *
 *   - `pratica`: a competência que o dia a dia da área exercita (o motor pratica
 *     um pouco por ano, além do que o ofício já pratica);
 *   - `salario`: o que o mercado paga a mais (ou a menos) por quem domina a área;
 *   - `peso`: o quanto a área pesa na cabeça (plantão, prazo, risco) — vai para o
 *     estresse do ano, como qualquer outro fator;
 *   - `vagas`: as vagas que procuram exatamente essa área (e reconhecem quem a tem);
 *   - `desafio`: o caso grande com a cara da área.
 *
 * As chaves são os nomes das áreas em `sistemas/oficios` (o que a pessoa escolheu
 * fica salvo pelo nome: `Trabalho.areas`).
 */

import type { Dominio } from '../tipos';

export interface AreaProfissional {
  /** O que a área é, em uma frase (a tela da escolha). */
  descricao: string;
  /** O que muda na vida (a consequência dita antes de escolher). */
  muda: string;
  pratica?: Partial<Record<Dominio, number>>;
  salario?: number;
  peso?: number;
  vagas?: string[];
  desafio?: { texto: string; deu: string; naoDeu: string };
}

export const AREAS_PROFISSIONAIS: Record<string, AreaProfissional> = {
  // Tecnologia (ti, dados)
  'segurança': { descricao: 'Proteger sistemas: achar a brecha antes de quem não deveria.', muda: 'Vagas de segurança da informação passam a te procurar; os incidentes viram seus — de madrugada, às vezes.', pratica: { programacao: 0.3, exatas: 0.1 }, salario: 1.08, peso: 3, vagas: ['analista_seguranca'], desafio: { texto: 'Um alerta às duas da manhã: alguém está tentando entrar pela porta dos fundos do sistema.', deu: 'Você fechou a porta e achou quem tinha deixado a chave. O relatório subiu até a diretoria.', naoDeu: 'Descobriram tarde demais: dados vazaram, e a reunião de segunda foi sobre você.' } },
  'dados': { descricao: 'Fazer os números falarem: bancos, análises, modelos de previsão.', muda: 'As vagas de dados reconhecem a sua estrada; a matemática volta a ser ferramenta de todo dia.', pratica: { exatas: 0.35, programacao: 0.15 }, salario: 1.05, peso: 1, vagas: ['analista_dados', 'cientista_dados'], desafio: { texto: 'A previsão que o seu modelo fez para a diretoria errou feio — e a reunião é amanhã.', deu: 'Você refez o modelo de madrugada e explicou o erro com clareza. A diretoria passou a confiar mais nos números — e em você.', naoDeu: 'A explicação não convenceu. Tiraram o projeto da sua mão.' } },
  'infraestrutura': { descricao: 'Manter tudo de pé: servidores, redes, a nuvem, o plantão.', muda: 'Vagas de infraestrutura abrem; o plantão de fim de semana entra na conta.', pratica: { programacao: 0.25 }, salario: 1.04, peso: 2, vagas: ['engenheiro_infra'], desafio: { texto: 'O sistema caiu numa sexta à noite e ninguém sabe por quê.', deu: 'Às quatro da manhã, voltou. Na segunda, o diretor sabia o seu nome.', naoDeu: 'Não achou a causa. Voltou sozinho, sem explicação — e a cobrança ficou.' } },
  'produto': { descricao: 'Decidir o que construir: ouvir quem usa, negociar com quem paga, priorizar.', muda: 'Menos código, mais gente: a liderança e a conversa crescem; vagas de produto passam a fazer sentido.', pratica: { lideranca: 0.3, comunidade: 0.1 }, salario: 1.06, peso: 1, vagas: ['gerente_produto'], desafio: { texto: 'O lançamento é em duas semanas, e o maior cliente pediu uma mudança que vira tudo de cabeça para baixo.', deu: 'Você negociou um meio-termo e o lançamento saiu no prazo. O cliente renovou.', naoDeu: 'O lançamento atrasou um mês, e o cliente foi embora mesmo assim.' } },
  // Direito
  'direito de família': { descricao: 'Divórcios, guardas, inventários: a lei no meio das famílias.', muda: 'Casos que pesam na cabeça; clientes que viram indicação para a família inteira.', pratica: { comunidade: 0.2 }, salario: 0.97, peso: 2, desafio: { texto: 'Uma disputa de guarda que já passou por dois advogados chegou a você.', deu: 'O acordo saiu sem que as crianças precisassem escolher um lado. A família indicou você a outras três.', naoDeu: 'A guarda foi para o outro lado. Você levou o processo para casa por semanas.' } },
  'direito trabalhista': { descricao: 'Patrão e empregado: rescisões, acordos, audiências em série.', muda: 'Volume grande de causas, honorários menores e mais constantes.', pratica: { humanas: 0.2 }, salario: 0.98, peso: 1, desafio: { texto: 'Uma ação coletiva de quarenta trabalhadores contra a mesma empresa caiu no escritório.', deu: 'O acordo coletivo saiu, e o escritório ganhou nome entre os sindicatos.', naoDeu: 'A empresa ganhou em primeira instância. Quarenta pessoas esperando uma resposta sua.' } },
  'direito criminal': { descricao: 'Defesa e acusação: júri, prazos curtos, delegacia de madrugada.', muda: 'Mais adrenalina, mais estresse — e casos que podem dar nome.', pratica: { linguagens: 0.25 }, salario: 1.02, peso: 3, desafio: { texto: 'Um júri popular, cidade inteira de olho, e o réu jura inocência.', deu: 'O júri absolveu. A cidade comentou por semanas — e o telefone não parou.', naoDeu: 'O réu foi condenado. Você vai recorrer, mas a derrota ficou.' } },
  'direito empresarial': { descricao: 'Contratos, sociedades, fusões: a lei a serviço do negócio.', muda: 'Clientes que pagam melhor e cobram mais; menos tribunal, mais reunião.', pratica: { exatas: 0.1, lideranca: 0.1 }, salario: 1.12, peso: 1, desafio: { texto: 'Uma fusão de duas empresas da região, com prazo para assinar até sexta.', deu: 'Assinaram na sexta às onze da noite. Os honorários vieram com um convite para outros negócios.', naoDeu: 'O negócio desandou numa cláusula que você não viu. O cliente não esqueceu.' } },
  // Odontologia
  'ortodontia': { descricao: 'Aparelhos e alinhamento: tratamentos longos, pacientes que voltam todo mês.', muda: 'Agenda previsível e fidelizada; adolescentes e pais na sala de espera.', salario: 1.1, peso: 0, desafio: { texto: 'Um caso de mordida cruzada que outro colega desistiu de tratar.', deu: 'Dois anos depois, o sorriso apareceu na foto de formatura do paciente. A mãe indicou a escola inteira.', naoDeu: 'O tratamento empacou; o paciente foi procurar outro consultório.' } },
  'implantes': { descricao: 'Cirurgia e prótese: procedimentos caros, de precisão.', muda: 'Renda maior por paciente — e um erro custa mais caro.', salario: 1.18, peso: 2, desafio: { texto: 'Uma reabilitação completa da boca de um paciente que já perdeu quase todos os dentes.', deu: 'A reabilitação deu certo. O paciente voltou a comer de tudo — e contou para todo mundo.', naoDeu: 'Um dos implantes não integrou. Refazer custou caro, e a confiança também.' } },
  'endodontia': { descricao: 'O canal: dor, urgência, o dente que ninguém mais salva.', muda: 'Encaminhamentos de outros dentistas; urgências fora de hora.', salario: 1.05, peso: 1, desafio: { texto: 'Um canal que outro profissional começou e não terminou, com o paciente em dor.', deu: 'Você salvou o dente. O colega que encaminhou passou a mandar todos os casos difíceis.', naoDeu: 'O dente não resistiu. Não foi culpa sua — mas o paciente acha que foi.' } },
  'odontopediatria': { descricao: 'Dentes de criança: paciência, medo, pais nervosos.', muda: 'Pacientes que crescem com você; uma clínica mais barulhenta e mais leve.', pratica: { comunidade: 0.15 }, salario: 0.98, peso: 1, desafio: { texto: 'Uma criança de cinco anos que nenhum dentista conseguiu atender.', deu: 'Na terceira consulta, a criança abriu a boca rindo. Os pais choraram.', naoDeu: 'A criança não deixou. Os pais foram para outro consultório.' } },
  // Educação
  'alfabetização': { descricao: 'Ensinar a ler e escrever: o primeiro passo de tudo.', muda: 'As turmas pequenas, os anos iniciais — e a chance de ver alguém ler pela primeira vez.', pratica: { linguagens: 0.25 }, salario: 1, peso: 1, desafio: { texto: 'Uma turma de terceiro ano em que metade ainda não lê.', deu: 'No fim do ano, a turma leu em voz alta na festa da escola. A direção notou.', naoDeu: 'O ano foi uma guerra. Metade da turma ainda não lê, e você sabe disso.' } },
  'matemática': { descricao: 'Fazer a matemática caber na cabeça de quem tem medo dela.', muda: 'Olimpíadas, reforço, aulas particulares que aparecem sozinhas.', pratica: { exatas: 0.3 }, salario: 1.03, peso: 1, desafio: { texto: 'A escola quer levar uma equipe à olimpíada de matemática — e quer você à frente.', deu: 'A equipe trouxe duas medalhas. Um dos alunos disse que quer ser professor.', naoDeu: 'A equipe não passou da primeira fase. Os alunos riram — você, menos.' } },
  'educação inclusiva': { descricao: 'Garantir que todo aluno aprenda: deficiência, atraso, o caso que a escola não sabia atender.', muda: 'Um trabalho mais lento e mais fundo; famílias que não esquecem.', pratica: { comunidade: 0.25 }, salario: 1, peso: 2, desafio: { texto: 'Um aluno com autismo chegou à escola sem nenhum apoio, e a família está desesperada.', deu: 'No fim do semestre, o aluno participou da apresentação da turma. A família mandou uma carta.', naoDeu: 'Faltou apoio da escola, e o aluno foi transferido. Você ficou com a sensação de falha.' } },
  'coordenação pedagógica': { descricao: 'Organizar o ensino de outros professores: planejamento, formação, conflitos.', muda: 'Sai da sala, entra na gestão: a direção fica mais perto, a sala mais longe.', pratica: { lideranca: 0.3 }, salario: 1.08, peso: 2, desafio: { texto: 'Os professores da escola estão em guerra com a direção, e pediram que você medie.', deu: 'A reunião terminou com um acordo. A direção passou a ouvir você antes de decidir.', naoDeu: 'Os dois lados saíram achando que você tomou partido do outro.' } },
  // Enfermagem
  'terapia intensiva': { descricao: 'A UTI: alarmes, monitores, gente entre a vida e a morte.', muda: 'Mais técnica, mais pressão, um adicional no salário — e plantões que pesam.', pratica: { ciencias: 0.2 }, salario: 1.08, peso: 3, desafio: { texto: 'Faltou gente na UTI: pediram para você segurar a escala de um mês difícil.', deu: 'O mês passou, os pacientes também — bem. A chefia não esqueceu.', naoDeu: 'Um erro de cansaço, sem gravidade, mas ficou no prontuário e na cabeça.' } },
  'emergência': { descricao: 'O pronto-socorro: tudo chega ao mesmo tempo.', muda: 'Decisões em segundos; o corpo cansa mais depressa.', pratica: { ciencias: 0.15 }, salario: 1.05, peso: 3, desafio: { texto: 'Um acidente com muitas vítimas chegou à emergência no meio do seu plantão.', deu: 'A equipe salvou todo mundo que podia ser salvo. No fim do plantão, ninguém conseguia falar.', naoDeu: 'Nem todos chegaram a tempo. Você foi para casa e não dormiu.' } },
  'saúde da família': { descricao: 'O posto do bairro: visitas, vacinas, as mesmas famílias por anos.', muda: 'Um ritmo mais humano; o bairro passa a conhecer você pelo nome.', pratica: { comunidade: 0.3 }, salario: 0.96, peso: 0, desafio: { texto: 'Um surto de dengue no bairro, e a equipe do posto é pequena.', deu: 'O surto passou mais depressa no seu bairro do que no resto da cidade. O posto ganhou nome.', naoDeu: 'Os casos se espalharam. Faltou gente, faltou repelente, faltou tempo.' } },
  'pediatria': { descricao: 'Crianças internadas e os pais ao lado da cama.', muda: 'Um trabalho delicado, que comove e cansa de outro jeito.', pratica: { comunidade: 0.15 }, salario: 1, peso: 2, desafio: { texto: 'Um bebê prematuro que ninguém da equipe consegue acalmar.', deu: 'O bebê dormiu no seu colo, e os pais finalmente também. Teve alta semanas depois.', naoDeu: 'O bebê precisou ser transferido. Você acompanhou de longe, sem notícias.' } },
  // Engenharia
  'estruturas': { descricao: 'Calcular o que fica de pé: vigas, fundações, laudos.', muda: 'Projetos com assinatura e responsabilidade; o cálculo vira rotina.', pratica: { exatas: 0.35 }, salario: 1.06, peso: 2, desafio: { texto: 'Um prédio antigo com rachaduras: pediram o seu laudo, e os moradores esperam lá fora.', deu: 'O laudo encontrou o problema a tempo. Os moradores voltaram para casa um mês depois, em segurança.', naoDeu: 'O laudo foi contestado por outro engenheiro, e a briga foi parar na Justiça.' } },
  'gestão de obras': { descricao: 'O canteiro: prazos, equipes, fornecedores, chuva.', muda: 'Muita gente para comandar; liderança cresce, a agenda encolhe.', pratica: { lideranca: 0.3 }, salario: 1.05, peso: 2, desafio: { texto: 'Uma obra atrasada precisa de alguém à frente. Quem assumir leva a culpa ou o crédito.', deu: 'Entregou no prazo. O seu nome começou a aparecer nas reuniões.', naoDeu: 'O atraso continuou — agora com o seu nome.' } },
  'projetos': { descricao: 'Desenhar antes de construir: o escritório, o software, as revisões.', muda: 'Trabalho de mesa e prazo; menos canteiro, mais precisão.', pratica: { exatas: 0.2, desenho: 0.1 }, salario: 1.02, peso: 1, desafio: { texto: 'O cliente mudou o projeto pela quinta vez, e a prefeitura pede tudo até o fim do mês.', deu: 'O projeto foi aprovado na primeira tentativa. O cliente prometeu o próximo.', naoDeu: 'A prefeitura devolveu o projeto com dezessete exigências.' } },
  'manutenção industrial': { descricao: 'Fazer a fábrica não parar: máquinas, turnos, peças que faltam.', muda: 'Chamados fora de hora; a indústria passa a disputar você.', pratica: { exatas: 0.15 }, salario: 1.04, peso: 2, desafio: { texto: 'A linha de produção parou e cada hora parada custa uma fortuna.', deu: 'A linha voltou em seis horas. A diretoria da fábrica passou a chamar você pelo nome.', naoDeu: 'Faltou a peça; a linha ficou parada três dias, e alguém precisava de um culpado.' } },
  // Contábil
  'área fiscal': { descricao: 'Impostos: a lei que muda todo ano e o prazo que não muda.', muda: 'Clientes que dependem de você em março; uma especialidade que sempre tem procura.', pratica: { exatas: 0.2 }, salario: 1.05, peso: 2, desafio: { texto: 'Uma mudança de última hora na lei de impostos, e trinta clientes ligando no mesmo dia.', deu: 'Ninguém pagou multa. Dois clientes novos chegaram por indicação.', naoDeu: 'Um cliente pagou multa por um erro no meio da correria. Ele não esqueceu.' } },
  'departamento pessoal': { descricao: 'Folha, férias, admissões: a vida das empresas por dentro.', muda: 'Um trabalho constante e sem susto — menos glamour, mais estabilidade.', pratica: { comunidade: 0.1 }, salario: 0.98, peso: 0, desafio: { texto: 'Uma empresa cliente vai demitir cinquenta pessoas, e quer tudo calculado em uma semana.', deu: 'Tudo calculado e pago certo. Ninguém agradeceu — que é o elogio da área.', naoDeu: 'Um cálculo saiu errado e virou processo trabalhista contra o cliente.' } },
  'auditoria': { descricao: 'Conferir as contas dos outros — e achar o que ninguém queria que fosse achado.', muda: 'Viagens a clientes, prazos curtos, salário melhor.', pratica: { exatas: 0.25 }, salario: 1.12, peso: 2, desafio: { texto: 'Os números de um cliente grande não fecham — e o dono jura que está tudo certo.', deu: 'Você achou o buraco e documentou tudo. O relatório mudou a empresa.', naoDeu: 'O dono convenceu a sua chefia de que não era nada. O relatório foi arquivado.' } },
  'contabilidade rural': { descricao: 'As contas do campo: safra, cooperativa, crédito agrícola.', muda: 'Clientes no interior; a temporada da colheita vira a sua também.', pratica: { campo: 0.1 }, salario: 1, peso: 1, desafio: { texto: 'Uma cooperativa inteira quer reorganizar as contas antes da próxima safra.', deu: 'As contas da cooperativa ficaram em ordem antes da safra. O crédito saiu.', naoDeu: 'A safra veio antes da organização. O crédito atrasou, e os cooperados reclamaram de você.' } },
  // Comunicação
  'política': { descricao: 'Cobrir o poder: assembleias, bastidores, fontes que somem.', muda: 'Pautas que incomodam; ameaças e prêmios na mesma medida.', pratica: { escrita: 0.2, humanas: 0.15 }, salario: 1.03, peso: 2, desafio: { texto: 'Uma pauta de política que incomoda gente poderosa caiu na sua mão.', deu: 'A reportagem repercutiu. Veio ameaça — e veio prêmio.', naoDeu: 'A matéria caiu na revisão. O editor pediu para você "esfriar".' } },
  'economia': { descricao: 'Mercado, inflação, empresas: explicar o dinheiro para quem não entende de dinheiro.', muda: 'Fontes no mercado; uma editoria que paga um pouco melhor.', pratica: { escrita: 0.15, exatas: 0.15 }, salario: 1.06, peso: 1, desafio: { texto: 'Um balanço de uma empresa da cidade com números que não batem.', deu: 'A reportagem saiu antes de todo mundo e a empresa teve de se explicar.', naoDeu: 'A empresa desmentiu, e o jornal recuou. Você ficou sozinh{o} na história.' } },
  'cultura': { descricao: 'Livros, shows, cinema: escrever sobre quem cria.', muda: 'Menos dinheiro, mais convite; os artistas da cidade passam a te conhecer.', pratica: { escrita: 0.25 }, salario: 0.94, peso: 0, desafio: { texto: 'Um artista famoso aceitou uma entrevista longa — só com você.', deu: 'A entrevista virou a capa do caderno e foi compartilhada no país inteiro.', naoDeu: 'O artista se arrependeu e pediu para cortar metade. Sobrou pouco.' } },
  'esporte': { descricao: 'O jogo, o vestiário, o torcedor: a cobertura de fim de semana.', muda: 'Fins de semana trabalhando; acesso a quem o país inteiro conhece.', pratica: { escrita: 0.15, comunidade: 0.1 }, salario: 1, peso: 1, desafio: { texto: 'Um escândalo no clube da cidade, e só você tem a fonte.', deu: 'A notícia saiu primeiro com você. Os outros jornais citaram o seu nome.', naoDeu: 'A fonte negou tudo depois da publicação, e você ficou expost{o}.' } },
  // Psicologia
  'crianças e adolescentes': { descricao: 'Atender quem ainda está crescendo — e os pais que vêm junto.', muda: 'Escolas passam a encaminhar; o consultório ganha brinquedos.', pratica: { comunidade: 0.2 }, salario: 0.98, peso: 1, desafio: { texto: 'Uma escola pediu ajuda com um adolescente em crise que ninguém consegue alcançar.', deu: 'O adolescente voltou à escola. A coordenação passou a encaminhar outros casos a você.', naoDeu: 'Ele parou de ir às sessões. Você soube depois que mudou de cidade.' } },
  'casais e famílias': { descricao: 'Atender a relação, não a pessoa: brigas, separações, recomeços.', muda: 'Sessões que viram campo de batalha; indicações de boca em boca.', pratica: { comunidade: 0.2 }, salario: 1.04, peso: 2, desafio: { texto: 'Um casal que já decidiu se separar quer tentar uma última vez.', deu: 'Eles ficaram juntos — e aprenderam a brigar de outro jeito.', naoDeu: 'Eles se separaram. Talvez fosse o melhor, mas pesou.' } },
  'trabalho e carreira': { descricao: 'O sofrimento do trabalho: burnout, demissão, a carreira que não fecha.', muda: 'Empresas contratam você; o horário fica mais comercial.', pratica: { lideranca: 0.1 }, salario: 1.1, peso: 1, desafio: { texto: 'Uma empresa quer que você atenda a equipe inteira depois de uma onda de afastamentos.', deu: 'A empresa mudou o jeito de trabalhar depois do seu relatório. Os afastamentos caíram.', naoDeu: 'A empresa usou o seu nome num programa de fachada. Você saiu.' } },
  'luto': { descricao: 'Acompanhar quem perdeu alguém.', muda: 'Um trabalho pesado e necessário; hospitais passam a chamar você.', pratica: { comunidade: 0.25 }, salario: 0.98, peso: 3, desafio: { texto: 'Uma família que perdeu um filho de repente pediu atendimento para todos.', deu: 'Meses depois, a família voltou a se sentar junta à mesa. Mandaram uma foto.', naoDeu: 'Uma das sessões terminou mal, e você levou o peso para casa.' } }
};

export const areaProfissional = (nome?: string): AreaProfissional | undefined => (nome ? AREAS_PROFISSIONAIS[nome] : undefined);
